### ISSUE TITLE
Syntax for CSS modules

### ISSUE THREAD

**Issue by dotnil** [erzu/oceanify#11]
两种使用场景：

1. CSS 模块之间的依赖
2. JS 模块依赖 CSS 模块（module），组成一个组件（component）

后者比较容易达成一致，直接 require('./some.css') 就可以了。是否支持 https://github.com/css-modules/css-modules 再议。

前者是本文讨论重点，目前比较纠结的地方有：

1. 入口代码的写法
2. 引用（声明）依赖的方式

针对入口代码，有两种方式：

```jade
!= linkTag('/app.css')
link(rel='stylesheet', href='/app.css')
```

这里假设 app.css 代码如下：

```css
/*
 *= require('./base')
 *= require('./iconfont')
 *= require('./layout')
 */

/* styles */
```

前者效仿 Rails 里的 Sprockets，在开发模式下实际渲染的时候，会展开为：

```html
<link rel="stylesheet" href="base.css">
<link rel="stylesheet" href="iconfont.css">
<link rel="stylesheet" href="layout.css">
<link rel="stylesheet" href="app.css">
```

在上线前，则通过 `rake assets:precompile` 任务来压缩、合并样式文件，从而兼得开发时的便利和上线时的性能优化。

后者，`link(rel='stylesheet', href='/app.css')` 这种用法，则等同于直接写 `<link>` 标签，由 Oceanify 在响应 app.css 请求的时候提供合并好的 app.css

不过，也不是必须这么做，如果我们采用 `@import` 作为引用依赖的方式，那么在开发时，我们就可以不合并样式，靠原生的 `@import` 即可。也就是说 app.css 可以写成这样：

```css
@import './base.css'
@import './iconfont.css'
@import './layout.css'

/* styles */
```

在上线合并的时候，交给 `oceanify.compileAll()` 处理掉这些 `@imports`。

所以大家不妨投票，选择入口代码写法：

1. `!= linkTag` 
2. `<link>` 直接写

以及模块声明方式：

1. `/*= require('./base') */`
2. `@import './base.css'`

我倾向选择 2, 2

**Comment by daiheitan** [comment]
2 2

**Comment by dotnil** [comment]
@kfitfk 2 2

**Comment by dotnil** [comment]
@chenhui5416 2 2

就这么定啦，入口和依赖声明均为标准写法。

后者还有个小细节，`@import` 后面还可以跟上 media query，也可以 `@import url(http://)`，例如：

```css
@import url("fineprint.css") print;
@import url("bluish.css") projection, tv;
@import 'custom.css';
@import url("chrome://communicator/skin/");
@import "common.css" screen, projection;
@import url('landscape.css') screen and (orientation:landscape);
```

本次不考虑 `@import url(http://)` 这种情况；如果后边有 media query，则打包的时候转变为（以最后一条为例）：

```css
@media (screen and (orientation:landscape)) {
  /* styles */
}
```

参考链接： 
- https://developer.mozilla.org/en-US/docs/Web/CSS/@import

**Comment by dotnil** [comment]
不处理 js 模块里的 require 的话，用 [postcss/postcss-import](https://github.com/postcss/postcss-import) 就够了 :joy:
