### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by daiheitan** [erzu/oceanify#13]
1. https://github.com/erzu/oceanify/blob/master/index.js#L277
这里感觉第二个exists判断应该在第一个里面

2. https://github.com/erzu/oceanify/blob/master/index.js#L358
这里如果已经拿到js/css，不应该继续yield next。
在kb里面，可能会被后续的router覆盖，而导致oceanify 失效

**Comment by dotnil** [comment]
第一个没看懂；第二个昨天我也发现啦，已经改了
