### ISSUE TITLE
parseAlias is error when the bower.json main is a array

### ISSUE THREAD

**Issue by chenhui5416** [erzu/oceanify#8]
https://github.com/erzu/oceanify/blob/master/lib/parseAlias.js#L49
http://bower.io/docs/creating-packages/#main

bower 的main 可以是Array， 处理时没有考虑到，导致 path.join 的参数中的main是一个array，而导致报错。
https://github.com/erzu/oceanify/blob/master/lib/parseAlias.js#L56

**Comment by dotnil** [comment]
具体哪个包？

**Comment by dotnil** [comment]
https://github.com/nnnick/Chart.js
